service: hello-world
release: "test-release"
repo: "git@github.com:Ferlab-Ste-Justine/ferlease-playground.git"
repo_branch: main
git_ssh_key: "~/.ssh/id_rsa"
git_known_key: "github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg="
template_directory: "{{.RepoDir}}/ferlease-templates/{{.Service}}"