service: hello-world
release: "test"
environment: "qa"
repo: "git@github.com:Magnitus-/ferlease-playground.git"
ref: main
git_ssh_key: "~/.ssh/id_rsa"
git_known_key: "known_host"
template_directory: "{{.RepoDir}}/ferlease-templates/{{.Service}}"
commit_message: "{{ if eq .Operation \"release\" }}Adding{{ else }}Removing{{ end }} release {{.Release}} of service {{.Service}}"
push_retries: 60
push_retry_interval: "5s"