service: hello-world
release: "test"
environment: "qa"
repo: "git@github.com:Magnitus-/ferlease-playground.git"
ref: main
git_auth:
  ssh_key: "~/.ssh/id_rsa"
  known_key: "known_host"
#author:
#  name: "Eric Vallee"
#  email: "eric_vallee@webificservices.com"
#commit_signature:
#  key: gpg-keys/tester.asc
#  passphrase: gpg-keys/passphrase
#accepted_signatures: accepted-signatures
template_directory: "{{.RepoDir}}/ferlease-templates/{{.Service}}"
commit_message: "{{ if eq .Operation \"release\" }}Adding{{ else }}Removing{{ end }} release {{.Release}} of service {{.Service}}"
push_retries: 60
push_retry_interval: "5s"