service: hello-world
release: "test"
environment: "qa"
repo: "git@github.com:Ferlab-Ste-Justine/ferlease-playground.git"
ref: main
git_auth:
  ssh_key: "/opt/id_rsa"
  known_key: "/opt/known_host"
author:
  name: "Your Name"
  email: "your@email.com"
#commit_signature:
#  key: /opt/gpg-keys/tester.asc
#  passphrase: /opt/gpg-keys/passphrase
#accepted_signatures: /opt/accepted-signatures
template_directory: "{{.RepoDir}}/ferlease-templates/{{.Service}}"
commit_message: "{{ if eq .Operation \"release\" }}Adding{{ else }}Removing{{ end }} release {{.Release}} of service {{.Service}}"
push_retries: 60
push_retry_interval: "5s"